sudo: required
language: python
install: true

env:
  - TEST=integration-test
  - TEST=bandit
  - TEST=docker-bench-security

matrix:
  allow_failures:
    - env: TEST=bandit

services:
  - docker

before_script:
  - export -f travis_fold
  - export REPO=archerysec/archerysec
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`

script:
 - |
    echo "Running test=$TEST"
    case "$TEST" in
      integration-test)
        travis_fold start "integration-test"
        bash integration-test.sh || exit 1
        travis_fold end "integration-test"
        ;;
      sourceclear)
        ## Run the SRC:CLR Scan
        curl -sSL https://download.sourceclear.com/ci.sh | bash
        ;;
      bandit)
        # install bandit
        pip install bandit
        ## Run Bandit python static code
        bandit -r * -x venv
        ;;
      docker-bench-security)
        ## Run Docker Bench for Security
        git clone https://github.com/docker/docker-bench-security.git
        cd docker-bench-security
        sh docker-bench-security.sh
        ;;
    esac
